import { range } from 'd3-array';
import { randomNumber } from './utils';

export const numberData = range(50)
  .filter(() => randomNumber(1, 2) % 2)
  .map(i => ({
    key: randomNumber(i - 5, i + 5),
    data: randomNumber(1, 10)
  }))
  .sort((a, b) => (a > b ? -1 : a < b ? 1 : 0));

export const browserData = [
  { key: 'Chrome', data: 39360 },
  { key: 'Firefox', data: 2228 },
  { key: 'Internet Explorer', data: 100 },
  { key: 'Safari', data: 91 },
  { key: 'Microsoft Edge', data: 2636 }
];

// generated by numberData
export const histogramNumberData = [
  {
    key: 2,
    data: 9
  },
  {
    key: 3,
    data: 10
  },
  {
    key: 8,
    data: 8
  },
  {
    key: 14,
    data: 2
  },
  {
    key: 10,
    data: 7
  },
  {
    key: 8,
    data: 5
  },
  {
    key: 17,
    data: 3
  },
  {
    key: 13,
    data: 6
  },
  {
    key: 15,
    data: 10
  },
  {
    key: 15,
    data: 2
  },
  {
    key: 16,
    data: 10
  },
  {
    key: 23,
    data: 8
  },
  {
    key: 22,
    data: 10
  },
  {
    key: 24,
    data: 5
  },
  {
    key: 30,
    data: 7
  },
  {
    key: 28,
    data: 8
  },
  {
    key: 36,
    data: 6
  },
  {
    key: 33,
    data: 3
  },
  {
    key: 29,
    data: 3
  },
  {
    key: 31,
    data: 7
  },
  {
    key: 32,
    data: 5
  },
  {
    key: 37,
    data: 7
  },
  {
    key: 41,
    data: 4
  },
  {
    key: 40,
    data: 1
  },
  {
    key: 47,
    data: 10
  },
  {
    key: 42,
    data: 4
  },
  {
    key: 45,
    data: 5
  },
  {
    key: 42,
    data: 8
  },
  {
    key: 53,
    data: 3
  }
];
